
CREATE TABLE GERMAN_UNI_KB_DETAILS AS (
SELECT DISTINCT GERMAN_UNI_KB.FK_ITEMS,
GERMAN_UNI_KB.FK_KB_SECTORS,
GERMAN_UNI_KB.NAME,
GERMAN_UNI_KB.FK_INSTITUTIONS,
GERMAN_UNI_KB.PK_KB_INST,
GERMAN_UNI_KB.ADDRESS_FULL,
WOS_B_2019.ITEMS.DOI,
WOS_B_2019.ITEMS.ARTICLE_TITLE,
WOS_B_2019.ITEMS.PUBYEAR,
WOS_B_2019.ITEMS.DOCTYPE


FROM GERMAN_UNI_KB JOIN WOS_B_2019.ITEMS 
ON WOS_B_2019.ITEMS.PK_ITEMS =  GERMAN_UNI_KB.FK_ITEMS
);
