SELECT COUNT(DISTINCT FK_ITEMS),NAME,FK_KB_SECTORS,PK_KB_INST
FROM GESISNABEDIYARAND.GERMAN_UNI_KB_DETAILS
WHERE PUBYEAR BETWEEN 2008 AND 2018
AND DOCTYPE IN ('Review','Article')

GROUP BY FK_KB_SECTORS,PK_KB_INST,NAME
ORDER BY FK_KB_SECTORS,PK_KB_INST;